version: '3'
services:
  backend:
    build:
      context: backend
    ports:
      - "9091:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/personnel_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personnel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"